// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2gQyj1OGh7EejQGqGx5vOl1qNeH8-6Lo',
    appId: '1:358079743770:web:bb652ddc75d11f1831cea3',
    messagingSenderId: '358079743770',
    projectId: 'flutternotebook-2c3bc',
    authDomain: 'flutternotebook-2c3bc.firebaseapp.com',
    storageBucket: 'flutternotebook-2c3bc.firebasestorage.app',
    measurementId: 'G-L88JJEFZLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-hNpIxod9lT-WReuQ5Liwy-YnrorCVI',
    appId: '1:358079743770:android:893d3cd482e4216f31cea3',
    messagingSenderId: '358079743770',
    projectId: 'flutternotebook-2c3bc',
    storageBucket: 'flutternotebook-2c3bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-l3_q9JcKDTlNLzU5Kb1V2VTIMTWAZcI',
    appId: '1:358079743770:ios:c55853cd8c77253b31cea3',
    messagingSenderId: '358079743770',
    projectId: 'flutternotebook-2c3bc',
    storageBucket: 'flutternotebook-2c3bc.firebasestorage.app',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2gQyj1OGh7EejQGqGx5vOl1qNeH8-6Lo',
    appId: '1:358079743770:web:aa779979612bdb8931cea3',
    messagingSenderId: '358079743770',
    projectId: 'flutternotebook-2c3bc',
    authDomain: 'flutternotebook-2c3bc.firebaseapp.com',
    storageBucket: 'flutternotebook-2c3bc.firebasestorage.app',
    measurementId: 'G-CHNF3VTPMF',
  );
}
