import 'dart:core';
//Used Map for progmattic seeding
//Dummy_data generated by AI
final List <Map<String, dynamic>>DUMMY_NOTES =[
  {
    "id": "note_001",
    "title": "Grocery Shopping List",
    "content": "Milk, eggs, bread, coffee beans, spinach, and that new spicy cheese I saw last week. Don't forget the cat food!",
    "lastEdited": "2025-12-06T16:45:00.000Z"
  },

  {
    "id": "note_002",
    "title": "BLoC Pattern Review",
    "content": "Need to solidify understanding of BLoC architecture:\n1. Events: Inputs\n2. BLoC: Business Logic (maps Events to States)\n3. States: Outputs (used by UI)\n4. Repository: Data abstraction layer (Firestore communication).",
    "lastEdited": "2025-12-06T15:30:00.000Z"
  },

  {
    "id": "note_003",
    "title": "Book Idea",
    "content": "A sci-fi novel about a world where digital memories can be bought and sold, leading to a black market for forgotten childhoods. Protagonist is a 'memory cleaner' who restores corrupted data.",
    "lastEdited": "2025-11-28T09:10:00.000Z"
  },

  {
    "id": "note_004",
    "title": "Meeting Agenda",
    "content": "1. Q4 Financials review\n2. Project X roadmap\n3. Team retreat planning.",
    "lastEdited": "2025-12-05T14:00:00.000Z"
  }
];